In [1]:
import numpy as np

### Problem 1

In [2]:
H = [[2,0,0],[0,-3, 1j], [0, -1j, 1]]

In [3]:
eigvals, eigfuncs = np.linalg.eig(H)
print(f'Eigenvalues = {eigvals}')

Eigenvalues = [ 1.23606798+0.j -3.23606798+0.j  2.        +0.j]


In [4]:
eigf1, eigf2, eigf3 = eigfuncs

# Normalize eigenfunctions
def Norm_Eigf(eigf):
    scaling = np.sqrt(1/((eigf[0]**2)+(eigf[1]**2)+(eigf[2]**2)))
    return eigf*scaling

# Normalized eigenfunctions
eigf1 = Norm_Eigf(eigf1)
eigf2 = Norm_Eigf(eigf2)
eigf3 = Norm_Eigf(eigf3)

print(f'Eigf1 = {eigf1}')
print(f'Eigf2 = {eigf2}')
print(f'Eigf3 = {eigf3}')

Eigf1 = [-0.+0.j  0.+0.j  1.+0.j]
Eigf2 = [0.        +0.24293414j 1.02908551+0.j         0.        +0.j        ]
Eigf3 = [1.02908551+0.j         0.        +0.24293414j 0.        +0.j        ]


In [5]:
# Original wavefunction
O_wf = [1/2, 1/np.sqrt(2), 1/2]
print(O_wf)

[0.5, 0.7071067811865475, 0.5]


In [6]:
### Calculate weights for linear comination of H eigenvectors
W1 = np.dot(eigf1,O_wf)
W2 = np.dot(eigf2,O_wf)
W3 = np.dot(eigf3,O_wf)

### Normalize weights
scaling = np.sqrt(1/(W1**2 + W2**2 + W3**3))
W1 = W1*scaling
W2 = W2*scaling
W3 = W3*scaling

print(f'Weight for Eigf1: {W1}')
print(f'Weight for Eigf2: {W2}')
print(f'Weight for Eigf3: {W3}')

Weight for Eigf1: (0.5165453179290286-0.09019901004958847j)
Weight for Eigf2: (0.7736649373628922-0.005784340284189976j)
Weight for Eigf3: (0.5625581433339992+0.08464220210703408j)


In [7]:
# Create wavefunction

### Answer to Problem 1
print(f'Wavefunction {O_wf} = {W1}*{eigf1} +       {W2}*{eigf2} +        {W3}*{eigf3}')

Wavefunction [0.5, 0.7071067811865475, 0.5] = (0.5165453179290286-0.09019901004958847j)*[-0.+0.j  0.+0.j  1.+0.j] +       (0.7736649373628922-0.005784340284189976j)*[0.        +0.24293414j 1.02908551+0.j         0.        +0.j        ] +        (0.5625581433339992+0.08464220210703408j)*[1.02908551+0.j         0.        +0.24293414j 0.        +0.j        ]


### Problem 2

In [8]:
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.animation import FuncAnimation
from IPython.display import display, Image, HTML

In [9]:
# Define Constants
k = 2
mu = 1
h_bar = 1.054e-34
alpha = np.sqrt(k*mu/(h_bar**2))

###
w = np.sqrt(k/mu)
w0 = w/2
w1 = 3*w/2

In [10]:
def momentum(t):
    return -np.sqrt(alpha/2)*h_bar*np.sin(t*w)

In [11]:
# Lists
x_data = []
y_data = []

# Graph Properties
fig,ax = plt.subplots()
ax.set_xlim(-3e-17,3e-17)
ax.set_ylim(0,12)
ax.set_xlabel('<p>')
ax.set_ylabel('time')
ax.set_title('Particle Movement as a Function of Time t')
line, = ax.plot(0,0,label='Position over Time')
leg = ax.legend()
ax.grid(True)

# Animation function which updates figure data.  This is called sequentially
def animate(i):
    x_data.append(momentum(i))
    y_data.append(i)
    
    line.set_xdata(x_data)
    line.set_ydata(y_data)
    return line,

# Call the animator.  blit=True means only re-draw the parts that have changed.
anim = FuncAnimation(fig, animate, frames=np.linspace(0,10,1000))

plt.close(anim._fig)

# Call function to display the animation
HTML(anim.to_html5_video())

### Problem 4

In [12]:
A = [[1, -1j],[1j, -1]]

eigvals, eigfuncs = np.linalg.eig(A)
print(eigvals)

[ 1.41421356+0.j -1.41421356+0.j]


In [13]:
print(eigfuncs)

[[0.92387953+0.j         0.        +0.38268343j]
 [0.        +0.38268343j 0.92387953+0.j        ]]


In [14]:
scaling = np.sqrt((3-2*np.sqrt(2))/(4-2*np.sqrt(2)))
print(scaling)

print(scaling*(1/(1-np.sqrt(2))))

0.3826834323650896
-0.9238795325112862


### Problem 6

In [15]:
P = [[0, 1, 0], [1, 0, 1], [0, 1, 0]]
print(P)

[[0, 1, 0], [1, 0, 1], [0, 1, 0]]


In [16]:
P_squared = np.dot(P,P)
print(P_squared)

[[1 0 1]
 [0 2 0]
 [1 0 1]]


In [17]:
Ly = [[0,-1j/np.sqrt(2),0],[1j/np.sqrt(2),0,-1j/np.sqrt(2)],[0,1j/np.sqrt(2),0]]

eigvals, eigfuncs = np.linalg.eig(Ly)
print(eigvals)
print(eigfuncs)

[ 1.00000000e+00+0.j  5.45028821e-17+0.j -1.00000000e+00+0.j]
[[-0.        -5.00000000e-01j  0.70710678+0.00000000e+00j
   0.        +5.00000000e-01j]
 [ 0.70710678+0.00000000e+00j  0.        +5.85895972e-17j
   0.70710678+0.00000000e+00j]
 [ 0.        +5.00000000e-01j  0.70710678-0.00000000e+00j
  -0.        -5.00000000e-01j]]
